/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(preamble.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(7ce2f89dad5c95a56a123d11871bad67)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <air_modes/preamble.h>
// pydoc.h is automatically generated in the build directory
#include <preamble_pydoc.h>

void bind_preamble(py::module& m)
{

    using preamble    = ::gr::air_modes::preamble;


    py::class_<preamble, gr::block, gr::basic_block,
        std::shared_ptr<preamble>>(m, "preamble", D(preamble))

        .def(py::init(&preamble::make),
           py::arg("channel_rate"),
           py::arg("threshold_db"),
           D(preamble,make)
        )
        




        
        .def("set_rate",&preamble::set_rate,       
            py::arg("channel_rate"),
            D(preamble,set_rate)
        )


        
        .def("set_threshold",&preamble::set_threshold,       
            py::arg("threshold_db"),
            D(preamble,set_threshold)
        )


        
        .def("get_rate",&preamble::get_rate,       
            D(preamble,get_rate)
        )


        
        .def("get_threshold",&preamble::get_threshold,       
            D(preamble,get_threshold)
        )

        ;




}








