/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(slicer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(de5bad12b8ae0f22c88c9cd886eaf8cc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <air_modes/slicer.h>
// pydoc.h is automatically generated in the build directory
#include <slicer_pydoc.h>

void bind_slicer(py::module& m)
{

    using slicer    = ::gr::air_modes::slicer;


    py::class_<slicer, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<slicer>>(m, "slicer", D(slicer))

        .def(py::init(&slicer::make),
           py::arg("queue"),
           D(slicer,make)
        )
        



        ;




}








